import { bodyPane, contentPane, navPane } from "@/styles/panes";
import type { Metadata } from "next";
import "./globals.css";
import { heading, lowSubtext, subtext } from "@/styles/prose";

export const metadata: Metadata = {
	title: "Queercraft News Network",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="oled">
			<body className={bodyPane()}>
				<header className={navPane()}>
					<div className={contentPane({ flex: "row" })}>
						<h1
							className={heading({ size: "xl", weight: "black" })}
						>
							The Queercraft News Network
						</h1>
					</div>
				</header>

				<main className={contentPane({ padding: "on" })}>
					{children}
				</main>

				<footer className={navPane()}>
					<div className={contentPane({ flex: "col" })}>
						<div>
							<p className={subtext()}>
								Copyright &copy; Queercraft News Network 2023.
							</p>
							<small className={lowSubtext()}>
								This site is not affiliated with, reccomended
								by, or otherwise endorsed in any form by{" "}
								<a href="https://queercraft.net/">Queercraft</a>{" "}
								or Prism.
							</small>
						</div>
					</div>
				</footer>
			</body>
		</html>
	);
}
